# This is a basic workflow to help you get started with Actions

name: Scripted Pipeline

# Controls when the workflow will run
on:
  push:
    branches:
    - 'feature-testing'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, World!'

  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo 'Pretending to build...'
           sleep 5 # Simulate work

  Results:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job completed at $(date)"
