# This is a basic workflow to help you get started with Actions

name: Generate ASCII Artwork

# Controls when the workflow will run
on:
  push:
    branches:
    - 'feature-testing'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-artwork:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: |-
            # Build a message by invoking ADVICESLIP API
            curl -s https://api.adviceslip.com/advice > advice.json
            cat advice.json

                        
            # Test to make sure the advice message has more than 10 words.
            cat advice.json | jq -r .slip.advice > advice.message
            [ $(wc -w < advice.message) -gt 10 ] && echo "Advice has more than 10 words" || (echo "Advice - $(cat advice.message)  has 10 words or less" && exit 1)
            
            # Deploy
            sudo apt-get install cowsay -y
            echo $PATH
            export PATH="$PATH:/usr/games:/usr/local/games"
            cat advice.message | cowsay -f $(ls /usr/share/cowsay/cows | shuf -n 1)
